version: '3.8'

services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      # - "9411:9411"
      # - "4317:4317"
      # - "4318:4318"
      # - "14250:14250"
      # - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      # - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - o11y-poc


  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      # - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      # - OTEL_EXPORTER_OTLP_INSECURE=true
      # - OTEL_RESOURCE_ATTRIBUTES=service.name=otel-collector
      # - OTEL_LOG_LEVEL=DEBUG
    command: ["--config=/etc/otel-collector-config.yaml"]
    depends_on:
      - jaeger
    networks:
      - o11y-poc

#app services

  home-service:
    image: home-service
    build:
      context: ../services/home-node.js
      dockerfile: ./Dockerfile
      args:
        - PORT=8080
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - OTEL_COLLECTOR_URL=http://otel-collector:4318
      - PRODUCTS_SERVICE_URL=http://products-service:8081
      - CATEGORIES_SERVICE_URL=http://categories-service:8082
      - OTEL_RESOURCE_ATTRIBUTES=service.name=home-service
      - OTEL_SERVICE_NAME=home-service
    depends_on:
      - otel-collector
      - products-service
      # - categories-service
    networks:
      - o11y-poc

  products-service:
    image: products-service
    build:
      context: ../services/products-go
      dockerfile: ./Dockerfile
      args:
        - PORT=8081
    ports:
      - "8081:8081"
    environment:
      - APP_PORT=8081
      - SALES_SERVICE_URL=http://sales-service:8083
      - OTEL_COLLECTOR_URL=http://otel-collector:4318
      - OTEL_RESOURCE_ATTRIBUTES=service.name=products-service
      - OTEL_SERVICE_NAME=products-service
    depends_on:
      - otel-collector
    networks:
      - o11y-poc

  categories-service:
    image: categories-service
    build:
      context: ../services/categories-php
      dockerfile: ./Dockerfile
      args:
        - PORT=8082
    ports:
      - "8082:8082"
    environment:
      - APP_PORT=8082
      - OTEL_RESOURCE_ATTRIBUTES=service.name=categories-service
      - OTEL_SERVICE_NAME=categories-service
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_PHP_AUTOLOAD_ENABLED=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/json
    depends_on:
      - otel-collector
    networks:
      - o11y-poc

  sales-service:
    image: sales-service
    build:
      context: ../services/sales-java
      dockerfile: ./Dockerfile
      args:
        - PORT=8083
    ports:
      - "8083:8083"
    environment:
      - APP_PORT=8083
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_RESOURCE_ATTRIBUTES=service.name=sales-service
      - OTEL_SERVICE_NAME=sales-service
    depends_on:
      - otel-collector
    networks:
      - o11y-poc
networks:
  o11y-poc:

